# <font color="Red"> Hypothesis Testing </font>

### <font color="Blue"> Q.1. A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions. </font>


In [10]:
import numpy as np
import pandas as pd 
from scipy import stats

In [2]:
df=pd.read_csv("C:/Users/pcc/Downloads/Cutlets.csv")

In [3]:
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

H0: Mu1-Mu2 = 0 Dimeter of cutlet unit A and Unit B has no significant difference.

H1: Mu1-Mu2 != 0 Dimeter of cutlet unit A and Unit B has significant difference.

In [4]:
stats.ttest_ind(df["Unit A"],df["Unit B"])

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

#### From above P-value we can say that there is significant difference in diameter of Unit A and Unit B.

###  <font color="Blue"> Q.2. A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch. Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.</font>

In [5]:
df1=pd.read_csv("C:/Users/pcc/Downloads/LabTAT.csv")

In [6]:
df1.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

H0: Mu1 = M2 = M3 = M4 There is no significant difference of avg TAT among Laboratories.

H1: Mu1 != M2 != M3 != M4 There is significant difference of avg TAT among Laboratories.

In [7]:
anova=stats.f_oneway(df1["Laboratory 1"],df1["Laboratory 2"],df1["Laboratory 3"],df1["Laboratory 4"])
anova

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

#### From above P-value we can say that there is no significant difference of avg TAT among Laboratories.

### <font color ="Blue">  Q.3. Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.</font>


In [8]:
df2=pd.read_csv("C:/Users/pcc/Downloads/BuyerRatio.csv")

In [9]:
df2

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [11]:
data=np.array([[50,142,131,70],[435,1523,1356,750]])
data

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

H0: the buyer ratio of male and female is independent of each other.

H1: the buyer ratio of male and female is dependent of each other.

In [12]:
stats.chi2_contingency(data) #(Chi-square statistics, P value, df, expected value)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

#### P value is greater than 0.05, that is the buyer ratio of male and female is independent of each other.

### <font color="Blue"> Q.4. TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences </font>


In [13]:
df3=pd.read_csv("C:/Users/pcc/Downloads/Costomer+OrderForm.csv")

In [14]:
df3

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [17]:
df3["Phillippines"].value_counts(),df3["Indonesia"].value_counts(),df3["Malta"].value_counts(),df3["India"].value_counts()

(Error Free    271
 Defective      29
 Name: Phillippines, dtype: int64,
 Error Free    267
 Defective      33
 Name: Indonesia, dtype: int64,
 Error Free    269
 Defective      31
 Name: Malta, dtype: int64,
 Error Free    280
 Defective      20
 Name: India, dtype: int64)

In [18]:
data1=np.array([[271,267,269,280],[29,33,31,20]])
data1

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

H0: Defective of  4 centers are independent of each other.
    
H1: Defective of  4 centers are dependent of each other.

In [19]:
stats.chi2_contingency(data1)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

#### P value is greater than 0.05, that is defective of  4 centers are independent of each other